services:
  - type: web
    name: ai-chat-backend
    env: python
    buildCommand: ./build.sh
    startCommand: node server.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: NODE_VERSION
        value: 16
    healthCheckPath: /health